# Generated by Django 3.2.25 on 2024-11-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaysNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
